spring.application.name=spring-boot-admin-server

server.port=9000
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=ALWAYS

#spring.boot.admin.ui.cache.no-cache=true
#spring.boot.admin.ui.extension-resource-locations=file:../spring-admin-admin-ui/target/dist/
#spring.boot.admin.ui.cache-templates=false

# Security
server.servlet.session.cookie.same-site=lax

# Enable instance authentication for accessing client actuator endpoints
spring.boot.admin.instance-auth.enabled=true